{
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "language": "node_js",
  "node_js": 7,
  "script": [
    "yarn install",
    "yarn test",
    "yarn build"
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}