cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  7 # use node version 7
branches:
  only: 
  - master # auto build and deploy in only master branch
script: # run after installed
  - yarn install # install node module
  - yarn test
  - yarn build # build project
install:
  yarn global add firebase-tools # install firebase-cli
after_success:
  - firebase use --token ${FIREBASE_TOKEN} # set firebase token
  - firebase use --add ${PROJECT_ID} # set current project
  - firebase deploy --non-interactive --token "${FIREBASE_TOKEN}" # deploy project
notifications:
  webhooks:
    urls:
      - https://api.ghostinspector.com/v1/suites/5981a3d3ed42cd3010099683/execute/?apiKey=a9baa3187c5bbae79b492d3e60bc2ca9068f2cba
    on_success: always
    on_failure: never